// Le hub : INDEX n'est pas qu'une vitrine, chaque app s'ouvre d'ici. « Les apps » est un tableau des départs
// (une ligne par app, son statut vérifié en direct, le bouton pour l'ouvrir) ; dans chaque app, l'onglet
// « ← Index » ramène au hub. D'après packages/projects (liste, liens, statut) et packages/ui (index-bar.js).
// Brouillons, à relire.
module.exports = {
  fr: {
    tab: "Les apps",
    openApp: "Ouvrir une app",
    allProjects: "Tous les projets",
    label: "Index · le hub",
    title: "Les <em>départs</em>",
    intro: "Mes apps tournent pour de vrai : ouvrez-en une d'ici. Dans chacune, l'onglet « ← Index » vous ramène. Le statut est vérifié toutes les heures.",
    introShort: "Mes apps tournent pour de vrai : ouvrez-en une d'ici, l'onglet « ← Index » vous ramène.",
    board: "Départs",
    checked: "Statut vérifié il y a 6 min",
    cols: { num: "N°", app: "App", dest: "Destination", gate: "Porte", status: "Statut" },
    status: { on: "En ligne", wake: "Se réveille", off: "Hors ligne", dl: "À télécharger", here: "Vous y êtes", arch: "Archive" },
    open: "Ouvrir →",
    download: "Télécharger ↓",
    code: "Le code ↗",
    fiche: "La fiche →",
    archives: "Archives · sans départ",
    archivesShort: "Les archives : Métro Pathfinder, API REST .NET, Visit Match, Galaxy Escape →",
    legend: [["on", "En ligne : l'app répond"], ["wake", "Se réveille : quelques secondes"], ["off", "Hors ligne : je suis prévenu"]],
    pageTitle: "INDEX — les apps",
    dest: {
      Magellan: "Le globe de mes voyages",
      Cancionero: "L'espagnol en chansons",
      Mithril: "Le coffre à mots de passe, sous Windows",
      Tonalli: "Un rituel à deux, chaque jour",
      "gym-picker": "La salle la moins embouteillée",
      Hublot: "Le guet des prix des vols",
      INDEX: "Ce site, et le dépôt qui réunit tout",
      "Métro Pathfinder": "Le plus court chemin dans le métro",
      "API REST .NET": "Des microservices C#, tests d'abord",
      "Visit Match": "Des voyageurs solo qui se trouvent",
      "Galaxy Escape": "Une course sans fin dans l'espace",
    },
    // L'onglet « ← Index », tel qu'il apparaît dans chaque app.
    tabSpec: {
      title: "L'onglet <em>« ← Index »</em>",
      intro: "Dans chaque app, un petit onglet fixe, en bas à gauche, ramène à INDEX. Il garde la matière du voyage sans toucher au design de l'app : il vit dans son propre Shadow DOM, n'a besoin d'aucune police, et s'efface quand l'app est installée sur l'écran d'accueil, ou à l'impression.",
      inApps: "Dans les apps : l'écran entier, puis son coin à taille réelle",
      states: "Ses états",
      stateNames: ["Au repos", "Au survol", "Au clavier"],
      grounds: ["Sur fond sombre", "Sur fond clair"],
      specs: [
        ["Où", "En bas à gauche, à 8 px du bord (et des encoches du téléphone)"],
        ["Quoi", "« ← Index », puis le numéro de l'entrée"],
        ["Vers", "La fiche de l'app sur INDEX ; de là, les autres apps sont à un onglet"],
        ["Jamais", "Dans l'app installée (PWA) ni à l'impression"],
        ["Code", "packages/ui, index-bar.js : le même dans toutes les apps"],
      ],
      pageTitle: "INDEX — l'onglet « ← Index »",
    },
  },
  en: {
    tab: "Apps",
    openApp: "Open an app",
    allProjects: "All projects",
    label: "Index · the hub",
    title: "<em>Departures</em>",
    intro: "My apps run for real: open one from here. In each, the “← Index” tab brings you back. Status is checked every hour.",
    introShort: "My apps run for real: open one from here, the “← Index” tab brings you back.",
    board: "Departures",
    checked: "Status checked 6 min ago",
    cols: { num: "No.", app: "App", dest: "Destination", gate: "Gate", status: "Status" },
    status: { on: "Live", wake: "Waking up", off: "Down", dl: "Download", here: "You are here", arch: "Archive" },
    open: "Open →",
    download: "Download ↓",
    code: "Code ↗",
    fiche: "Project page →",
    archives: "Archives · no departures",
    archivesShort: "The archives: Métro Pathfinder, .NET REST API, Visit Match, Galaxy Escape →",
    legend: [["on", "Live: the app responds"], ["wake", "Waking up: a few seconds"], ["off", "Down: I get alerted"]],
    pageTitle: "INDEX — apps",
    dest: {
      Magellan: "My travels on a globe",
      Cancionero: "Spanish through songs",
      Mithril: "A password safe for Windows",
      Tonalli: "A daily ritual for two",
      "gym-picker": "The least jammed gym",
      Hublot: "A lookout for flight prices",
      INDEX: "This site, and the repo behind it all",
      "Métro Pathfinder": "The shortest route on the metro",
      "API REST .NET": "C# microservices, test-first",
      "Visit Match": "Solo travellers finding each other",
      "Galaxy Escape": "An endless run through space",
    },
    tabSpec: {
      title: "The <em>“← Index”</em> tab",
      intro: "In every app, a small fixed tab in the bottom-left corner leads back to INDEX. It keeps the journey's materials without touching the app's design: it lives in its own Shadow DOM, needs no font, and steps aside when the app is installed on the home screen, or printed.",
      inApps: "In the apps: the whole screen, then its corner at actual size",
      states: "Its states",
      stateNames: ["At rest", "On hover", "Keyboard focus"],
      grounds: ["On a dark background", "On a light background"],
      specs: [
        ["Where", "Bottom left, 8 px from the edge (and from the phone's notches)"],
        ["What", "“← Index”, then the entry's number"],
        ["To", "The app's page on INDEX; from there, every other app is one tab away"],
        ["Never", "In the installed app (PWA) or in print"],
        ["Code", "packages/ui, index-bar.js: the same in every app"],
      ],
      pageTitle: "INDEX — the “← Index” tab",
    },
  },
  // Les portes (hébergeurs) en court, pour le tableau : la fiche de chaque app donne le détail.
  gate: { Magellan: "Cloudflare", Cancionero: "Vercel", Mithril: "GitHub", Tonalli: "Vercel", "gym-picker": "Cloudflare", Hublot: "GitHub", INDEX: "Cloudflare" },
};
